version: '3.9'
services:
  nginx:
    image: nginx:1.24-alpine
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/nginx:/etc/nginx/conf.d:ro"
      - "./data/certbot/conf:/etc/letsencrypt:ro"
      - "./data/certbot/www:/var/www/certbot:ro"
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - "./data/certbot/conf:/etc/letsencrypt:rw"
      - "./data/certbot/www:/var/www/certbot:rw"
