version: '3.9'
services:
  nginx:
    image: nginx:1.24-alpine
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - run
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/nginx/conf:/etc/nginx/conf.d:ro"
      - "./data/nginx/dh:/etc/nginx/dh:ro"
      - "./data/certbot/conf/:/etc/nginx/ssl/:ro"
      - "./data/certbot/www:/var/www/certbot:ro"
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - "./data/certbot/conf:/etc/letsencrypt:rw"
      - "./data/certbot/www:/var/www/certbot:rw"
      - "./data/certbot/log:/var/log/letsencrypt:rw"
    networks:
      - init
      - run

networks:
  init:
  run:
