version: '3.9'
services:
  nginx:
    image: nginx:1.24-alpine
    restart: always
    networks:
      - init
    ports:
      - "80:80"
    volumes:
      - "./data/nginx-init:/etc/nginx/conf.d"
      - "./data/certbot/www:/var/www/certbot:ro"
  certbot:
    image: certbot/certbot
    command: "certonly --webroot --webroot-path /var/www/certbot/ -d ${HOST} --non-interactive"
    volumes:
      - "./data/certbot/conf:/etc/letsencrypt:rw"
      - "./data/certbot/www:/var/www/certbot:rw"
      - "./data/certbot/log:/var/log/letsencrypt:rw"
    networks:
      - init
    depends_on:
      - nginx

networks:
  init:
